### ISSUE TITLE
If child doesn't exist for particular parent, child element is still present and contains a non empty array

### ISSUE THREAD

**Issue by mooreds** [restsql/restsql#23]
If you are writing a parent child query and the child doesn't exist, if you are outputing json, you will see this: 

`{ "listings" : { ...listingdata...,
            "photos": [
                {  }
            ]
        },
....
}`

If outputting XML, the photos element is correctly an empty element.  In JSON it should be an empty array, not an array containing an object.

**Comment by BobbyT** [comment]
Hi,

I have the same problem (version 0.8.11).

The xml output shows me an empty element `<myproperty/>`
But when I switch to json it looks like this:
```
myproperty: [
  {
    "id": null,
    "attr": null
  }
]
```

any idea why this is happening?

**Comment by restsql** [comment]
BobbyT - Kinda lost without some context. 

Please post the resource definition and the request URL + body.

Thanks
