### ISSUE TITLE
Problem starting service on tomcat

### ISSUE THREAD

**Issue by SebCou** [restsql/restsql#39]
Hi.
I have a problem to run this service on a osx tomcat. This is the error I get from the Tomcat log:
Aug 12, 2013 3:11:06 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /usr/local/apache-tomcat-7.0.42/webapps/restsql-0.8.6.war
Aug 12, 2013 3:11:06 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/Library/Tomcat/webapps/restsql-0.8.6/WEB-INF/lib/servlet-api.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class
Aug 12, 2013 3:11:07 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class org.apache.catalina.deploy.ApplicationListener@2d35da43
java.lang.UnsupportedClassVersionError: org/restsql/service/LifecycleListener : Unsupported major.minor version 51.0 (unable to load class org.restsql.service.LifecycleListener)

I guess I shouldn't be getting this error since I use the unmodified restsql WAR package. Anybody knows what could be wrong?

/Sebastian

**Comment by woodz-** [comment]
Aloha Sebastian,
could you please post the log of the successful running solution? I am interested wheter you still get the "jar not loaded" thing. I am currently trying to get restsql to work on tomcat 7 with java 7/8 on suse 13.2 and always get that info. Since I have a lot of trouble, I just wanted to know whether that's occurring on your system.

thx.
woodz

**Comment by restsql** [comment]
What version of restsql is this? 

Could you post the relevant portion of the startup log please?

You've followed the http://restsql.org/doc/Deployment.html war mode instructions?

**Comment by woodz-** [comment]
yes I did, and started a new issue: https://github.com/restsql/restsql/issues/61
