### ISSUE TITLE
trouble on open SUSE 13.2

### ISSUE THREAD

**Issue by woodz-** [restsql/restsql#61]
- os: open SUSE 13.2
- tomcat: Apache Tomcat/7.0.55
- java:
  - java version "1.8.0_25"
  - Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
  - Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode, sharing)
- mysql: Ver 14.14 Distrib 5.6.17, for Linux (i686) using  EditLine wrapper
- restSql: 0.8.9 (war mode)

Aloha,

I've difficulties on getting it to work. I was following the instructions of http://restsql.org/doc/Deployment.html. Then I found a sample which is using the HTTP API Explorer further down in the doc and I thought this would be a good point to start. The sakila database creation worked like a charm using the bash script. The explorer is even shown in the browser. But any request (the easiest would be a select I guess) seems not to trigger any servlet job. Instead I always receive the answer

`HTTP/1.1 404 Not Found`
`Content-Type: null`

 and the definition area remains empty (white). In the access log of tomcat there is a info telling me the path is not found. Something between the mapping of sqlresource.dir="/some/dir" to the /res part of the url seems not to work.
When the container initially gets loaded I receive a "jar not loaded" info message. While researching the github I found 3 further issues where this info message occurs (not necessarily discussed):
- https://github.com/restsql/restsql/issues/44
- https://github.com/restsql/restsql/issues/39
- https://github.com/restsql/restsql/issues/31

While I'm getting more and more clueless I am taking into account that this might be an issue. Although researching the net results in answers like "that does't matter" or "it's save to ignore this message".
Another topic is the CLASSPATH thing. I know, its not a restsql thing. But if you almost running out of ideas, everything might be adversely. It seems that on my distro tomcat doesm't make use of the environment variable $CLASSPATH. And some net research told me that either. After a long research I found this: https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/loader/VirtualWebappLoader.html. I edited the context.xml as it would be a class path environment variable. Since then I ultimately got the wistfully awaiting /var/log/restsql/internal.log.

Thanks in advance for any suggestion
- catalina startup log

`Jan 04, 2015 11:28:26 PM org.apache.catalina.core.AprLifecycleListener init`
`INFO: Loaded APR based Apache Tomcat Native library 1.1.30 using APR version 1.5.1.`
`Jan 04, 2015 11:28:27 PM org.apache.catalina.core.AprLifecycleListener init`
`INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].`
`Jan 04, 2015 11:28:28 PM org.apache.catalina.core.AprLifecycleListener initializeSSL`
`INFO: OpenSSL successfully initialized (OpenSSL 1.0.1i 6 Aug 2014)`
`Jan 04, 2015 11:28:29 PM org.apache.coyote.AbstractProtocol init`
`INFO: Initializing ProtocolHandler ["http-apr-8080"]`
`Jan 04, 2015 11:28:29 PM org.apache.coyote.AbstractProtocol init`
`INFO: Initializing ProtocolHandler ["ajp-apr-8009"]`
`Jan 04, 2015 11:28:29 PM org.apache.catalina.startup.Catalina load`
`INFO: Initialization processed in 3789 ms`
`Jan 04, 2015 11:28:29 PM org.apache.catalina.core.StandardService startInternal`
`INFO: Starting service Catalina`
`Jan 04, 2015 11:28:29 PM org.apache.catalina.core.StandardEngine startInternal`
`INFO: Starting Servlet Engine: Apache Tomcat/7.0.55`
`Jan 04, 2015 11:28:29 PM org.apache.catalina.startup.HostConfig deployWAR`
`INFO: Deploying web application archive /srv/tomcat/webapps/restsql-sdk.war`
`Jan 04, 2015 11:28:32 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom`
`INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [113] milliseconds.`
`Jan 04, 2015 11:28:33 PM org.apache.catalina.startup.HostConfig deployWAR`
`INFO: Deployment of web application archive /srv/tomcat/webapps/restsql-sdk.war has finished in 3,662 ms`
`Jan 04, 2015 11:28:33 PM org.apache.catalina.startup.HostConfig deployWAR`
`INFO: Deploying web application archive /srv/tomcat/webapps/restsql.war`
`Jan 04, 2015 11:28:33 PM org.apache.catalina.loader.WebappClassLoader validateJarFile`
`INFO: validateJarFile(/usr/share/tomcat/webapps/restsql/WEB-INF/lib/servlet-api.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class`
`Jan 04, 2015 11:28:37 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate`
`INFO: Initiating Jersey application, version 'Jersey: 1.5 01/14/2011 12:36 PM'`
`Jan 04, 2015 11:28:37 PM com.sun.jersey.server.impl.application.DeferredResourceConfig$ApplicationHolder <init>`
`INFO: Instantiated the Application class org.restsql.service.RestSqlApplication`
`Jan 04, 2015 11:28:39 PM org.apache.catalina.startup.HostConfig deployWAR`
`INFO: Deployment of web application archive /srv/tomcat/webapps/restsql.war has finished in 6,092 ms`
`Jan 04, 2015 11:28:39 PM org.apache.coyote.AbstractProtocol start`
`INFO: Starting ProtocolHandler ["http-apr-8080"]`
`Jan 04, 2015 11:28:39 PM org.apache.coyote.AbstractProtocol start`
`INFO: Starting ProtocolHandler ["ajp-apr-8009"]`
`Jan 04, 2015 11:28:39 PM org.apache.catalina.startup.Catalina start`
`INFO: Server startup in 10120 ms`
- restsql internal.log

`2015-01-04 23:28:37,005 [localhost-startStop-1] INFO org.restsql.internal- Loaded restsql properties from /etc/restsql/restsql.properties`
- tomcat access.log

`192.168.178.31 - - [04/Jan/2015:23:48:25 +0100] "GET /restsql-sdk/api-explorer/ HTTP/1.1" 200 9530`
`192.168.178.31 - - [04/Jan/2015:23:48:25 +0100] "GET /restsql-sdk/api-explorer/blank.html HTTP/1.1" 200 251`
`192.168.178.31 - - [04/Jan/2015:23:48:25 +0100] "GET /favicon.ico HTTP/1.1" 404 -`
`192.168.178.31 - - [04/Jan/2015:23:48:25 +0100] "GET /favicon.ico HTTP/1.1" 404 -`
`192.168.178.31 - - [04/Jan/2015:23:48:25 +0100] "GET /srv/tomcat/webapps/restsql-sdk/examples/conf/definition/Country HTTP/1.1" 404 -`
`192.168.178.31 - - [04/Jan/2015:23:48:45 +0100] "GET /srv/tomcat/webapps/restsql-sdk/examples/res/Country HTTP/1.1" 404 -`

**all other restsql logs are always 0 Byte of size**
- context.xml

<Context>

```
<!-- Default set of monitored resources -->
<WatchedResource>WEB-INF/web.xml</WatchedResource>

<!-- Uncomment this to disable session persistence across Tomcat restarts -->
<!--
<Manager pathname="" />
-->

<!-- Uncomment this to enable Comet connection tacking (provides events
     on session expiration as well as webapp lifecycle) -->
<!--
<Valve className="org.apache.catalina.valves.CometConnectionManagerValve" />
-->

<Parameter name="org.restsql.properties" value="/etc/restsql/restsql.properties" override="false" />

<Loader className="org.apache.catalina.loader.VirtualWebappLoader"
          virtualClasspath="/etc/restsql;/usr/share/java;
            /usr/share/tomcat/webapps"/>
```

</Context>

**Comment by restsql** [comment]
Sorry about all the trouble. The offending class is some overlap in restSQL's included servlet jar and Tomcat's native jar. I wouldn't worry about it. The jar not loaded in other posts were class versioning issues, e.g. running java 7 restsql version on a java 6 jre.

It looks like the war is loading properly. FYI: I've never tried this on Java 8, but I doubt it's an issue.

Now what URL are you using to access restSQL? The default would be http://host:port/restsql-0.8.9, unless you changed the war to restsql.war, in which case it would be http://host:port/restsql. Do you see a listing of functions? It's a static index file. If you click on Resources, all you see is a blank page? Usually if there is a config problem it will show an error. Go back to home and then to Configuration, then System. You can see if your /etc/restsql/restsql.properties is loading properly. It will local props in the first section and defaults in the second section. 

Your sqlresources.dir hopefully is not actually /some/dir but something like /etc/restsql/sqlresources, right?

Thanks,
Mark

**Comment by woodz-** [comment]
Aloha Mark,
I appreciate your time to give support, thanks for that.
I followed your suggestion to test http://host:port/restsql (not the sdk with its samples) and it worked like a charm. I didn't believe in the "jar not loaded" thing either. The wars are indeed only "restsql" and "restsql-sdk" since it has been sugggested by the doc.
Since I copied the resources from the sdk samlpe into the restsql resources dir, which by the way is "sqlresources.dir=/etc/restsql/sqlresources", I now can do everything via the Ressources function on the web page as I would have expected to do with the sdk's HTTP API explorer. Even the logs are now available including trace, access, error.
Now my only remaining question is: what do I need to reconfigure to switch to the sdk API explorer sample?
The following are two access logs for comparison.
from the API explorer: 
`192.168.178.31 - - [05/Jan/2015:14:32:11 +0100] "GET /srv/tomcat/webapps/restsql-sdk/examples/conf/definition/Country HTTP/1.1" 404 -`

from restsql:
`192.168.178.31 - - [05/Jan/2015:15:08:54 +0100] "GET /restsql/conf/definition/Country HTTP/1.1" 200 416`

Could it  be that the javascript of the API explorer needs some configuration maintenance? The url doesn't seem to get translated as it has been done by the restsql war. There is no such 'conf' dir as it resides in the restsql war

thanks, woodz

**Comment by restsql** [comment]
Set sqlresources.dir to the absolute path to the sdk's SQL resources dir. For example:

sqlresources.dir=/opt/tomcat/webapps/restsql-sdk/examples/sqlresources

Or you can copy the sqlresources contents to the existing /etc/... location. That way you don't need a restart.

When you hit /restsql/res you should see all the example sqlresources as well as your own. Keep in mind that the explorer expects Country to be in the root (/res/Country) so it has to be at the root of sqlresources.dir.
