### ISSUE TITLE
Can't extract or deploy war (EOFException, IllegalArgumentException)

### ISSUE THREAD

**Issue by jiraeval** [restsql/restsql#67]
Hi there!

I don't know is this a bug or some kind of feature or it's my fault, but, i can't neither  install war in Tomcat nor extract contents with jar tool or 7-zip.

Nevertheless jar-tool luckily extracts a pack of files, before throwing EOFException exception. Last extracted file was "WEB-INF/lib/jackson-core-2.5.0.jar" 

My environment:
restSQL wars: 0.8.7, 0.8.9, 0.8.10
Win7 Pro x64
Apache Tomcat 7 (jre 1.7.0_80)
7-zip
jar (tried with these jdk's jar tool: 1.6.0_45 and 1.8.0_45)

Tomcat error log:"IllegalArgumentException: Invalid or unreadable WAR file : error in opening zip file"
jar cmd-line error: "EOFException: Unexpected end of ZLIB input stream"
7-zip just don't opens file

Thank you in advance.

**Comment by restsql** [comment]
Hello jiraeval. Sorry you're having trouble just when you're just getting started.

I've never tried opening a jar file (war and ear files are the same format) with 7-zip. Not sure I've ever used it before. Can run a listing on it with jar -t {file-name}?

Sounds like the files are corrupted, but I believe they are good on restsql.org.

Did you download them with some special HTTP tool or a browser? Any chance it converted from binary to text?

- Mark

**Comment by jiraeval** [comment]
Good day Mark.
Thank you for fast response. Today i've tried to install resSQL 0.8.10 on my corporate notebook. The environment of home and corporate n'books are almost similiar, and it's goes fine, war-deployed and i can access it via browser. I'll try again this evening at home to deploy war-file. Maybe problem is in my inet home connection and for some reason downloaded file was corrupted.
By the way can you provide md5 hash or checksums for distributions?

Thank you.

**Comment by jiraeval** [comment]
Hi, again.

Glad to inform you that issue has resolved. At home I've downloaded war distribution one more time, and it worked, e.g. i had able to extract it by jar tool, browse by 7-zip archivator and install it in Tomcat.
I assume it was connection or distribution integrity problem.

**Comment by restsql** [comment]
Good to hear!
