### ISSUE TITLE
Not an issue per-se, but an open question.

### ISSUE THREAD

**Issue by noordawod** [restsql/restsql#68]
Hi all.

I'm doing a research and want to decide on a RESTful framework (with or without an ORM layer) to build on. However, this library's approach is very nice indeed and opens up a lot of possibilities for me.

So my question is: Is this library still in development? What's the roadmap?

**Comment by restsql** [comment]
Hello Noor.

This Mark Sawers the project lead. You can see from the release history on
restsql.org that there are about three releases

**Comment by restsql** [comment]
... a year. There are occasional contributions but I drive many of the enhancements. You're welcome to contribute or extend privately. The project uses the MIT license.

You can see the roadmap (a roughly ordered backlog) on restsql.org. 

Mark

**Comment by noordawod** [comment]
Many thanks, Mark. I'll try to contribute as much (and as needed) as possible once I start using the library.
