### ISSUE TITLE
Attribute IS NULL condition

### ISSUE THREAD

**Issue by cloehle** [restsql/restsql#69]
As far as I can tell, there is no way to query if an attribute is null like so:
select * from table where attr is null;
(This is using the HTTP API)

**Comment by restsql** [comment]
It doesn't look like there is support for that. It's a head scratcher. Hard
to believe the framework made it this far without a complaint on it.

We could do col-name=_null in the query string and post params. If that was
actually the value you wanted to search in, have it escaped like \_null.

Do you need to know in responses if a column is null vs some default (eg
blank string or zero int)? I forget if the attribute appears at all in the
response if it is null.

Mark

**Comment by cloehle** [comment]
I can pretty easily check if it is null on the client using JSON/XML(the attribute won't be present if null).
This just is a waste of bandwidth and client processing time ;)
My personal workaround is setting a default value instead of not setting the attribute at all, but I still think you should be able to check for NULL directly.
_null seems like a good idea to me.

**Comment by restsql** [comment]
Fixed with release 0.8.11
