### ISSUE TITLE
I think your website has been hacked

### ISSUE THREAD

**Issue by ryanpersaud** [restsql/restsql#71]
When I try to visit this link restsql.org/doc/SqlResourceRules.html, I get redirected to an unsavory site.

**Comment by restsql** [comment]
Looks fine to me. Perhaps you're system has been compromised?

**Comment by ryanpersaud** [comment]
Apparently Google has been compromised too:

![image](https://cloud.githubusercontent.com/assets/3010742/13555789/77b7cc10-e397-11e5-87fa-33ecdf32f294.png)

**Comment by ryanpersaud** [comment]
Interestingly, if you visit the following link from Google, you get redirected to the unsavory site, while if you cut and paste, you arrive at the expected site.

![image](https://cloud.githubusercontent.com/assets/3010742/13557134/88900924-e3b7-11e5-95fe-1fcde2c0dca7.png)

**Comment by restsql** [comment]
Thanks for the heads up! It was the same situation with yahoo and bing. I cleaned out dozes of rogue php files, uploaded the regular content, and changed all the passwords. Only possible way that stuff made it there is through their management tools or some brute force over ssh. When I complained to godaddy they tried to sell me an $84/yr security product.
