### ISSUE TITLE
Generating resource definitions

### ISSUE THREAD

**Issue by bhagy** [restsql/restsql#73]
I specified following, in restsql.properties file;
sqlresources.dir=$TOMCAT_HOME/webapps/restsql/sqlresources

When trying to create the resource definition using http://localhost:8080/restsql/tools/ , we can't just blank out the directory in the form.

If I entered a directory called myresources, then .xml file is created inside sqlresources/myresources folder. Then to access them, I need to change the url as http://localhost:8080/restsql/res/myresources.<table-name>. But just moving the generated files manually to sqlresources directory, we can access the resources using http://localhost:8080/restsql/res/<table-name>

What can I do to solve this issue, without changing the file locations manually?

**Comment by kolchagov** [comment]
Of course,
you can enter path like this: ../ 
then the generated resources are going to be placed exactly at specified folder.

**Comment by restsql** [comment]
Setting this as a feature request to enable blank directory name in sqlresource definition generation tool.
