### ISSUE TITLE
Pass url parameters for where clause value

### ISSUE THREAD

**Issue by ankur1000** [restsql/restsql#82]
Get URL to call the api stored in myapi.xml file:
http://IP:PORT/restsql/res/myapi?AnimalName=CAT

the query part of xml file:
**select animalId "Id" from animals where animalname = AnimalName**

I want to pass value for where clause through url. However I am getting error as "No valid parameters found". How do I pass where clause values through url parameters.

**Comment by restsql** [comment]
Hello Ankur1000. Drop the where clause from the resource SQL. The framework dynamically generates this for you on each request. Only include the columns you need. 

If there are multiple tables needed in the resource, then you use join on clauses or where with join columns.

**Comment by ankur1000** [comment]
Hi restsql, I am still getting error which says "No valid parameters found"

**Comment by restsql** [comment]
Please post your resource definition and your request details.
