### ISSUE TITLE
Extra 's' on table names in JSON response

### ISSUE THREAD

**Issue by cwstrommer** [restsql/restsql#83]
## System information:

* Restsql release 0.8.12
* Tomcat 8 / Java 7 (official Tomcat Docker container)

## Problem:

Let's say we have a resource on table 'foo'.  The XML query produces

```
<readResponse><foo ...
```

The JSON query should produce

```
{ "foo": [
    { ...
```

but it produces

```
{ "foos": [
    { ...
```

**Comment by restsql** [comment]
You can use the rowSetAlias attribute in the table metadata to depluralize it. See http://restsql.org/doc/Concepts.html#ColumnandTableAliases.

**Comment by cwstrommer** [comment]
@restsql Thanks, I was just reading up on the code and came to that same conclusion myself.
