### ISSUE TITLE
Changing base URL

### ISSUE THREAD

**Issue by ankur1000** [restsql/restsql#84]
How do I change base URl from http://localhost:8080/restsql/res/ to http://localhost:8080/abc/xyz/

**Comment by restsql** [comment]
The app servers generally assume the app path from the war name. So rename it to abc. Or if you've already started the server, stop it, and rename the auto-created dir in webapps. Same for the docker form. 

For the parts after /abc, you'd need a framework software change for res, conf, tools, etc. The resource name of course is the name of the file you choose, e.g. /abc/res/people.

There might be some alias capability in the Java servlet web.xml, but I'm not familiar with it.

Lastly you can put a reverse proxy like nginx in front of it and rewrite URLs.
