### ISSUE TITLE
compatible with Google App Engine ?

### ISSUE THREAD

**Issue by yiga2** [restsql/restsql#85]
Considering the limitation on sockets (https://cloud.google.com/appengine/docs/standard/java/sockets/), would restSQL work in GAE as a war file on Jetty ?

I like to use GAE to run a 3rd party j2ee app with h2 database as backend. restSQL would be a perfect add-on.

**Comment by restsql** [comment]
I'm not familiar with GAE, nor what this restriction covers. H2 is generally run in process, but if you ran it standalone, then yes there would be JDBC sockets opened across process, and possibly hosts, for each restsql request. There is no long running connection pool. Each request starts and stops a new connection/socket.

However, you're going to face a bigger issue. There is no explicit support for H2 in restsql. It's architected for easy extension to new databases, but that's a dev effort.

Regardless if you do go for an H2 extension, or convert to a supported db - mysql or postgresql - you might want to consider deploying as a container. restsql ships as a docker container, and you could deploy to google compute engine, along with a mysql or postgresql container.

Mark

**Comment by yiga2** [comment]
Thanks Mark - it turned out that there are too many restrictions to run a J2EE on AppEngine. Some will argue that AppEngine is not meant for that. So I am back on GCE (Google VM) so no socket issues if any. On that note H2 runs in embedded mode and would share the JVM started with restSQL and Tomcat.
Also, I am considering moving from h2 to CloudSQL, which is managed MySQL on Google Cloud.
restSQL should work on that.

**Comment by restsql** [comment]
H2 is probably best for some mobile app, or some dev environment. How would you ever scale it? Back it up? Run a reporting app on it. An enterprise-grade, managed database is likely best to build on.

Suggest you look at running restsql as a container. GKE is the service on the google cloud. I haven't used it. Only Amazon's analog - ECS. If it's anything like amazon's, you can define a service/task, pulling images directly from the official registry (hub.docker.com) and be up and running in minutes.

**Comment by yiga2** [comment]
Yep – container is the way we will go. Thanks for your continued efforts on restSQL !!

**Comment by restsql** [comment]
Thanks and Good luck!
